### PR TITLE
Improve layout avoid covering the buttons on low resolution devices

### PR DESCRIPTION
**Pull request by kaisar945**
- Before
image
- After
image

### CODE REVIEW

**Comment by pimterry** [comment]
Oh, interesting! Thanks for the contribution @kaisar945, excellent point.

I do agree this is better than the current behaviour here where the buttons disappear, although it would be nice if there was no need to scroll, and we do have some unnecessary whitespace left here...

Do you think it's easy to shrink the whitespace (e.g. above the Connected text) just on small screens, to help with this? I think we'd want to use the scrollview too just as a backup for really small cases, but it would be nice to avoid needing that where possible.

Out of interest, what device are you using where you're seeing this, and what's the resolution? I thought I'd tested most common small sizes, but this is clearly smaller than I was expecting.

**Comment by kaisar945** [comment]
Thank you for your reply, you are right I will try it.

This is my device resolution, it's not a real phone

Physical size: 480x960
Physical density: 240

**Comment by pimterry** [comment]
I'm still interested in this! Do you think you'll have any time soon to investigate tweaking the whitespace here?

**Comment by kaisar945** [comment]
Of course， I've been busy with work recently and almost forgot about this. I'll take some time to fix it as soon as possible.

**Comment by kaisar945** [comment]
Updated

**Comment by pimterry** [comment]
Thanks @kaisar945! Merged and released as v1.3.11 (building now, it'll be live on Google Play and auto-downloaded in HTTP Toolkit within a day or so)

**Comment by pimterry** [comment]
By the way, in case you're not aware, HTTP Toolkit Pro is free for contributors - I've set up an account linked to your Git commit email (j*.j*@gmail.com). Just click 'Get Pro' then 'Log into existing account' and enter your email there to log in. Thanks again!

**Comment by kaisar945** [comment]
> By the way, in case you're not aware, HTTP Toolkit Pro is free for contributors - I've set up an account linked to your Git commit email (j*.j*@gmail.com). Just click 'Get Pro' then 'Log into existing account' and enter your email there to log in. Thanks again!

Thank you for providing a powerful tool😃

**Pull request merged**
