### PR TITLE
Support adaptive icons

### PR DESCRIPTION
**Pull request by X1nto**
This PR enables support for Android's [adaptive icons](https://developer.android.com/develop/ui/views/launch/icon_design_adaptive), including the new Material You monochrome version:
| Before | After     |
|---------|---------|
| Screenshot_20230405-163002~2 |    Screenshot_20230406-000752~2 |

~*Note: Since I had no access to the original SVG of HTTPToolkit's icon, I had to make my own. It's super close to the original icon but you still might want to use your own original icon instead. I attached my recreation SVG file just in case: [http-toolkit-icons.zip](https://github.com/httptoolkit/httptoolkit-android/files/11159148/http-toolkit-icons.zip)*~

### CODE REVIEW

**Comment by pimterry** [comment]
Interesting! I'm definitely open to this. I'm not sure exactly how the adaptive icons etc work, so I'll look into that first, and I'll need to do some testing on devices to see how it appears everywhere.

A couple of things I notice here already though:

* It seems like the new icon here is noticeably smaller than the original, which leaves a lot of white space. Can you make it a bit bigger, so they match?
* This removes the reference to `@mipmap/ic_launcher_foreground`, but still leaves all the `app/src/main/res/mipmap-*/ic_launcher_foreground.png` logo files everywhere. Should those now be removed?

In case it's useful, the original SVG is here: 
logo-icon

I think when the icon was originally set up though, I used the Android new project tools, uploaded that SVG and then configured the zoom manually from there, so I'm not sure exactly what scaling that should use I'm afraid.

**Comment by pimterry** [comment]
I've also just noticed that the build isn't working - it seems that GitHub isn't running it at all. I think this might be due to an old OS configuration that they've now deprecated. I've just [fixed that](https://github.com/httptoolkit/httptoolkit-android/commit/71af10233b7abe59ef53f24b134c0fd3e8cf7ed5) on master, so if you rebase this PR then that should start working correctly.

**Comment by X1nto** [comment]
> I've also just noticed that the build isn't working - it seems that GitHub isn't running it at all. I think this might be due to an old OS configuration that they've now deprecated. I've just [fixed that](https://github.com/httptoolkit/httptoolkit-android/commit/71af10233b7abe59ef53f24b134c0fd3e8cf7ed5) on master, so if you rebase this PR then that should start working correctly.

Done!

**Comment by X1nto** [comment]
Hm, it seems like I accidentally pushed some .idea files. I suggest .gitignoring the whole .idea folder.

**Comment by X1nto** [comment]
> Interesting! I'm definitely open to this. I'm not sure exactly how the adaptive icons etc work, so I'll look into that first, and I'll need to do some testing on devices to see how it appears everywhere.
> 
> A couple of things I notice here already though:
> 
> * It seems like the new icon here is noticeably smaller than the original, which leaves a lot of white space. Can you make it a bit bigger, so they match?
> * This removes the reference to `@mipmap/ic_launcher_foreground`, but still leaves all the `app/src/main/res/mipmap-*/ic_launcher_foreground.png` logo files everywhere. Should those now be removed?
> 
> In case it's useful, the original SVG is here: logo-icon
> 
> I think when the icon was originally set up though, I used the Android new project tools, uploaded that SVG and then configured the zoom manually from there, so I'm not sure exactly what scaling that should use I'm afraid.

Oh, didn't see this comment. I'll update the monochrome accordingly.

**Comment by X1nto** [comment]
Updated both monochrome and mipmap icons, just to make them on par. Also removed all of the `@mipmap/ic_launcher_foreground` as per your observation since they're not used anywhere anymore.

**Comment by pimterry** [comment]
Thanks! I've forced push to rebase (instead of copying the commit) but otherwise this all looks good to me, nice work :+1:. I'll ship a new release with the update shortly.

By the way, in case you're not aware, HTTP Toolkit Pro is free for contributors - I've set up an account linked to your Git commit email, you can just click 'Get Pro' then 'Log into existing account' and enter your email there to log in. Thanks again!

**Comment by X1nto** [comment]
> By the way, in case you're not aware, HTTP Toolkit Pro is free for contributors - I've set up an account linked to your Git commit email, you can just click 'Get Pro' then 'Log into existing account' and enter your email there to log in. Thanks again!

Thank you! Have a nice day.

**Pull request merged**
